### ISSUE TITLE
Map doesn't show with zoom level greater than 8

### ISSUE THREAD

**Issue by Anasmasuris** [hiddewie/OpenRailwayMap-vector#291]
I've nocited recently that map doesn't load any vector layer with zoom greater than 8 - is this some maintenance thing or issue with missing (or uncoded) rendering for `railway:radio`?

![Image](https://github.com/user-attachments/assets/1c819c1a-a23b-4829-96e9-2d8fbd5fb898)

**Comment by wolfy1339** [comment]
With work on #231 some things might have been wonky for a bit

There isn't an icon for unknown radio railway signals which is why nothing is showing up

**Comment by hiddewie** [comment]
> I've nocited recently that map doesn't load any vector layer with zoom greater than 8

Yes I probably made a mistake somewhere in the tile rendering for Europe. The other regions seem to work. 

The tiles are split up between the entire planet (zooms 0-7) and per region (zooms 8+). I will take a look.

**Comment by hiddewie** [comment]
Missing radio icon has been fixed with [#292](https://github.com/hiddewie/OpenRailwayMap-vector/pull/292).

I am working on fixing the Europe and North America tiles for zooms >8.

**Comment by hiddewie** [comment]
I also opened https://github.com/maplibre/martin/issues/1758 to understand why martin is using much more memory than expected during startup.

**Comment by hiddewie** [comment]
I reverted the entire planet deployment, so only North-america and Europe remain (https://github.com/hiddewie/OpenRailwayMap-vector/pull/295). However those tile containers now also go out of memory, while they worked before.

**Comment by Anasmasuris** [comment]
The only thing that comes to my mind could be the addition to `railway:signal:radio` to the tags, that are imported - but I'm not certain whether this is related to the issue

**Comment by hiddewie** [comment]
Thanks for the comment. I think the data is not the problem, but the way the tiles are served (some combination of MBtiles, Docker and Martin).

I was looking into converting MBTile files into PMTile files (see some details in https://github.com/maplibre/martin/issues/1758#issuecomment-2745238918). Both the file sizes and memory usage seems promising. I will test-deploy that, to see if that makes things work again.

**Comment by hiddewie** [comment]
I deployed a small region with PMtiles instead of MBTiles. Both served by Martin. PMTiles seems to work. Now deploying the entire planet in https://github.com/hiddewie/OpenRailwayMap-vector/actions/runs/14008810469 to see if that fixes everything.

**Comment by hiddewie** [comment]
Deployment succeeded, the entire planet should be available again on https://openrailwaymap.fly.dev

**Comment by EHCG04** [comment]
Will there be new, up-to-date tiles deployed while the underlying issue with MBTiles is not fixed on their end? (Just curious as I've edited quite a bit in the last days) :)

**Comment by EHCG04** [comment]
> Tiles are being updated like normal.

Thanks! I've been refreshing and deleting my browser cache since this morning, and now it's all there. Sorry for the confusion.

**Comment by wolfy1339** [comment]
It seems the latest deployment failed, https://github.com/hiddewie/OpenRailwayMap-vector/actions/runs/14023876302

**Comment by hiddewie** [comment]
Yes, there is caching both in the browser and in the proxy. So even after a deployment it may take up to 24 hours for changes to show up. (The caching values are configured in https://github.com/hiddewie/OpenRailwayMap-vector/blob/298700dc13cd53f0d37637019207590891f7b25e/proxy.fly.toml#L31C22-L33)

**Comment by hiddewie** [comment]
> It seems the latest deployment failed, https://github.com/hiddewie/OpenRailwayMap-vector/actions/runs/14023876302

Yes Github made an internal server error for one set of tiles in the Asia region. So the Asia deployment failed for one day, but the other regions will still be updated.

And the most recent deployment https://github.com/hiddewie/OpenRailwayMap-vector/actions/runs/14047666280 worked again 🎉 

So should be all good.
